---
title: "cs3_gk_v1"
author: "G. Kapila"
date: "1/27/2021"
output: html_document
---

```{r setup, echo=TRUE, message=TRUE, warning=FALSE}
setwd('C:\\Users\\a0875458\\Documents\\My Data\\IDP\\Masters\\Sem 6 - 09 - 7333 - Quantifying The World\\Week 4 _20210127\\')

library(ggplot2)
library(dplyr)
library(lubridate)

df <- na.omit(read.csv("cherry_blossom_final.csv",na.strings = c("NR", "NA")))

```

```{r dataProcessing, echo=TRUE,message=TRUE, warning=FALSE}

df$age <- as.numeric(df$age)
df$time <- as.character(df$time)

yr_cnt <- count(df,year)

tformat <- hms(df$time)
df$tmins <- hour(tformat)*60 + minute(tformat)  + second(tformat)/60

df$ageRange = cut(df$age,breaks = c(0,15,25,45,65,90))

age_yr_cnt <- (df %>% group_by(ageRange) %>% count(year) %>% mutate(Nor = n/n[1])) %>% mutate(n_diff = n - lag(n))

df$ageRange_gran = cut(df$age,breaks = c(seq(0,90,10)))

age_gran_yr_cnt <- (df %>% group_by(ageRange_gran) %>% count(year) %>% mutate(Nor = n/n[1])) %>% mutate(n_diff = n - lag(n))

age_yr_time <- (df %>% group_by(ageRange_gran,year) %>% mutate(t_median = median(tmins)) %>% mutate(t_min = min(tmins)))

```

```{r analysis19, fig.width = 12,echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_yr_time, aes(x = ageRange_gran, y = t_min, fill = as.factor(year)))+
  geom_bar(position = "dodge2", stat="identity",width = 1)+
  labs(title="Runtime \n Different Age Group by Year",x="Age Group", y = "Runtime, minutes")+
  scale_fill_discrete()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis18, fig.width = 12,echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_yr_time)+
  geom_line(aes(x = year, y = t_min, color = ageRange_gran))+
  labs(title="Minimum runtime \n per Year by Age Group",x="Year", y = "Fastest Runtime, minutes")+
  scale_fill_discrete()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis17, fig.width = 12,echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_yr_time)+
  geom_line(aes(x = year, y = t_median, color = ageRange_gran))+
  labs(title="Median runtime \n per Year by Age Group",x="Year", y = "Median Runtime, minutes")+
  scale_fill_discrete()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis16, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(na.omit(df), aes(x = ageRange_gran, y = tmins))+
  geom_boxplot()+
  labs(title="Runtime Distribution by Age Group",x="Age Group", y = "Runtime, minutes")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis15, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(na.omit(df), aes(x = ageRange, y = tmins))+
  geom_boxplot()+
  labs(title="Runtime Distribution by Age Group",x="Age Group", y = "Runtime, minutes")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis14, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(df, aes(x = factor(year), y = tmins))+
  geom_boxplot()+
  labs(title="Runtime Distribution by Year",x="Year", y = "Runtime, minutes")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```



```{r analysis13, fig.width = 12,echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_yr_cnt, aes(x = ageRange, y = n_diff, fill = as.factor(year)))+
  geom_bar(position = "dodge2", stat="identity",width = 1)+
  labs(title="Women Participation Increase \n per Year by Age Group",x="Year", y = "Number of runners added, #")+
  scale_fill_discrete()+
  theme(plot.title = element_text(hjust = 0.5))
```



```{r analysis12, fig.width = 12,echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_gran_yr_cnt, aes(x = ageRange_gran, y = n_diff, fill = as.factor(year)))+
  geom_bar(position = "dodge2", stat="identity",width = 1)+
  labs(title="Women Participation Increase \n per Year by Age Group",x="Year", y = "Number of runners added, #")+
  scale_fill_discrete()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis11, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_yr_cnt[age_yr_cnt$ageRange == "(15,25]",], aes(x = ageRange, y = n_diff, fill = as.factor(year)))+
  geom_bar(position = "dodge2", stat="identity",width = 1)+
  labs(title="Women Participation Increase \n per Year 15-25 years Agegroup",x="Year", y = "#Women")+
  scale_fill_discrete()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis10, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_yr_cnt, aes(x = year, y = n))+
  geom_line(aes(color = ageRange))+
  labs(title="Women Participation Numbers \n by Age Group",x="Year", y = "Number of runners, #")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis9, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_gran_yr_cnt, aes(x = year, y = n))+
  geom_line(aes(color = ageRange_gran))+
  labs(title="Women Participation Numbers \n by Age Group",x="Year", y = "Number of runners, #")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis8, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_gran_yr_cnt, aes(x = year, y = Nor))+
  geom_line(aes(color = ageRange_gran))+
  labs(title="Relative Change in Women Participation Numbers \n by Age Group",x="Year", y = "Participation ratio (=n2012/n1999)")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis7, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_yr_cnt, aes(x = year, y = Nor))+
  geom_line(aes(color = ageRange))+
  labs(title="Relative Change in Women Participation Numbers \n by Age Group",x="Year", y = "Participation ratio (=n2012/n1999)")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis6, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(age_yr_cnt, aes(x = year, y = n))+
  geom_bar(stat="identity")+
  facet_wrap(~ageRange, ncol = 1)+
  labs(title="Women Participation by Year",x="Year", y = "Number of runners, #")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis1, echo=TRUE,message=TRUE, warning=FALSE}


ggplot(yr_cnt, aes(x = year, y = n))+
  geom_bar(stat="identity")+
  labs(title="Women Participation by Year",x="Year", y = "Number of runners, #")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis2, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(df, aes(x = factor(year), y = age))+
  geom_boxplot()+
  labs(title="Age Distribution by Year",x="Year", y = "Age")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis3, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(df, aes(age))+
  geom_density(aes(fill=factor(year)), alpha=0.3) + 
  labs(title="Age Distribution by Year",x="Age", y = "Density")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis4, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(df, aes(x=age, color = factor(year)))+
  geom_density() + 
  labs(title="Age Distribution by Year",x="Age", y = "Density")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r analysis5, echo=TRUE,message=TRUE, warning=FALSE}

ggplot(df, aes(x=age, color = factor(year)))+
  geom_density() + 
  labs(title="Age Distribution by Year",x="Age", y = "Density")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```