---
title: 'MSDS 7333 Spring 2021: Case Study 04 '
author: "Sachin Chavan,Tazeb Abera,Gautam Kapila,Sandesh Ojha"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  pdf_document:
    keep_tex: yes
    extra_dependencies: float
  word_document: default
  html_document:
    df_print: paged
subtitle: Influenza forecast
header-includes:
- \usepackage{siunitx}
- \newcolumntype{d}{S[table-format=3.2]}
- \usepackage{multicol}  
- \usepackage{float}  
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[L]{Case Study 03}
latex_engine: pdflatex
urlcolor: blue    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Introduction

**Influenza** most commonly known as **flu** is an infectious respiratory disease caused by virus. There four known variants of the Influenza. Type A , Type B, Type C and Type D. Based on historical data it occurs in winter or in monsoon season. There are several studies have been conducted on the causes of occurring in the specific season and one of the study has linked it to vitamin D levels in human [$^{[1]}$][References]. It's during winter or rainy season when people stay mostly indoors and are less expose to sun causing the fall of levels of vitamin D in people. Staying inside homes has also been seen as one of the reason of transmission the disease as people are in close contact of each other. That explains a bit of seasonal occurrence of the flu every year. These viruses infect nose, throat and lungs and leads to mild to severe illness and has been observed that it can also lead to death of proper attention is not given.

   Data shows that globally on an average 389K deaths occurs due to flu and it mostly affect people who are above 60 years of age[$^{[2]}$][References]. In the United States alone more than 200K hospitalization are due to Influenza every year[$^{[3]}$][References]. [Centers for Disease Control and Prevention](https://www.cdc.gov/) has reported range of death is between 3500 and 49K every year and costs the U.S. economy more than \$10 billions[$^{[4]}$][References].Out of many strains of the viruses few have potential to create pandemics/epidemics. One the deadliest pandemic occurred in year 1918 which infected 33% of the world population and caused 100 million deaths worldwide. It has been observed that such or less severe pandemic occurs 3 times in a century. As this is repeating phenomenon it becomes important to gather data on infection to take precautionary steps to contain the impact of virus to protect most vulnerable population. It helps to control and respond proactively to spread of the disease, arranging medical treatments accordingly and alert health officials in advance which potentially stops to become pandemic.

World Health Organization (WHO) plays an important role in keeping watch on such diseases as it occurs across the world. They established [Global Influenza Surveillance and Response System (GISRS)](http://www.who.int/influenza/gisrs_laboratory/en/) in 1952 to monitor Influenza and different strains and changes in viruses with the goal of reducing its impact and providing guidance to researchers to develop/enhance vaccine. Centers for Disease Control and Prevention and WHO works together to contain the virus and protect older population in the country.

With this initial background this case study provides different insights from the [data](https://apps.who.int/flumart/Default?ReportNo=12) that is publicly available on WHO's website. Study will analyze trends in the data to develop model to 2 week forecast of infections details of which is available in later section of this document.

# Business Understanding

The Influenza causes significant impact on the economy and puts additional burden health system every year. According to data adults with certain medical conditions and people above 60 years of age particularly affected by flu badly the end results in hospitalization. Sudden increase in patients puts pressure on Hospitals, Doctors, nurses and eventually affects treatments of patients. Knowing that such a diseases occurs every year requires monitoring, data collection and planning. There are several ways to control getting into such situation. Once of the way is vaccination before winter or monsoon starts, spreading awareness , face-masking etc. Another way to go one step further and provide forecast so that preventive actions can be taken at right time.Forecast can provide guidence to logistics for healthcare, e.g. start time of vaccinations, medical staff, arranging medicines, medical equipmments only when it is needed, alerting citizens to take precautionary steps like washing hands, physical distancing, using face masks etc. Which eventually may help to reduce number of patients and in turn pressure on health agencies. Therefore it is important to monitor such diseases by the way of collecting health data on regular basis so that preventive actions can be taken, to alert Health organizations in advance. THe goal of this case study is to obtain data that WHO has collected over the years and build and evaluate a model that will accurately forecast incidences of Influenza. 

## Objective

Download historical [data](https://apps.who.int/flumart/Default?ReportNo=12) that is available on the WHO website and build and evaluate a time series model (ARIMA) to provide accurate forecast of Influenza incidences.

\newpage
# Data Extraction & Evaluation

\newpage
# Modeling Building

\newpage
# Forecasting

\newpage
# Conclusions

\newpage
# References

1.  Cannell JJ, Vieth R, Umhau JC, Holick MF, Grant WB, Madronich S, et al. (December 2006). "Epidemic influenza and vitamin D". Epidemiology and Infection. 134 (6): 1129–40. doi:10.1017/S0950268806007175. PMC 2870528. PMID 16959053.
2. Paget J, Spreeuwenberg P, Charu V, Taylor RJ, Iuliano AD, Bresee J, et al. (December 2019). "Global mortality associated with seasonal influenza epidemics: New burden estimates and predictors from the GLaMOR Project". Journal of Global Health. 9 (2): 020421. doi:10.7189/jogh.09.020421. PMC 6815659. PMID 31673337.
3.  Thompson WW, Shay DK, Weintraub E, Brammer L, Cox N, Anderson LJ, et al. (January 2003). "Mortality associated with influenza and respiratory syncytial virus in the United States". JAMA. 289 (2): 179–86. doi:10.1001/jama.289.2.179. PMID 12517228. S2CID 5018362.
4. [Small Business and Technology Development Center article ](https://sbtdc.org/resources/recovery/pandemic-flu/)