---
title: "MSDS7333-Real Time Location Systems"
author: "Sachin Chavan"
date: "01/17/2021"
output:
  html_document:
    code_folding: show
    df_print: paged
    highlight: zenburn
    html_theme: readable
    keep_md: yes
    number_sections: yes
    theme: journal
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
txt <- readLines("data/offline.final.trace.txt")
```

# Load Data

```{r Data-Preparation}
processLine = function(x)
{
  tokens = strsplit(x, "[;=,]")[[1]]
  if (length(tokens) == 10)
    return(NULL)
  tmp = matrix(tokens[- (1:10)], ncol = 4, byrow = TRUE)
  cbind(matrix(tokens[c(2, 4, 6:8, 10)], nrow(tmp), 6, byrow = TRUE), tmp)
}

lines = txt[substr(txt, 1, 1) != "#"]
options(error = recover, warn = 1)
tmp = lapply(lines, processLine)
offline = as.data.frame(do.call("rbind", tmp),stringsAsFactors = FALSE)

names(offline) = c("time", "scanMac", "posX", "posY", "posZ",
                   "orientation", "mac", "signal",
                   "channel", "type")

numVars = c("time", "posX", "posY", "posZ",
            "orientation", "signal")
factors = c("mac", "channel", "scanMac","type")

offline[numVars] = lapply(offline[numVars], as.numeric)

offline[factors] = lapply(offline[factors], factor)
```

## Structure of the Data

```{r Dataset-Structure}
str(offline)
```


## Summary

```{r Summary, echo=FALSE}
summary(offline)
```

## Unique MAC addresses
```{r}
offline %>% count(mac) %>% arrange(n)
```
## Unique Scanning devices

Only one device was used

```{r}
offline %>% count(scanMac) %>% arrange(n)
```


## Channels 

```{r}
offline %>% count(channel) %>% arrange(n)
```
## Total Orientations

There are total 203 orientation recorded. Expected orientation in dataset are 8.

```{r}
offline$orientation <- as.numeric(offline$orientation)
offline %>% count(orientation) %>% arrange(orientation)
```
```{r}
unique(offline$type)
```


```{r}
offline = offline[offline$type == "3",]
offline$rawTime = offline$time
offline$time = offline$time/1000
class(offline$time) = c("POSIXt", "POSIXct")
roundOrientation = function(angles) {
 refs = seq(0, by = 45, length = 9)
 q = sapply(angles, function(o) which.min(abs(o - refs)))
 c(refs[1:8], 0)[q]
}
offline$angle = roundOrientation(offline$orientation)
locDF = with(offline, by(offline, list(posX, posY), function(x) x))
locDF = locDF[!sapply(locDF, is.null)]
locCounts = sapply(locDF, nrow)
locCounts = sapply(locDF,
    function(df)
     c(df[1, c("posX", "posY")], count = nrow(df)))
locCounts = t(locCounts)
plot(locCounts, type = "n", xlab = "", ylab = "")
text(locCounts, labels = locCounts[,3], cex = .8, srt = 45)
```

```{r}
offline %>% count(mac) %>% arrange(n)
```